language: ruby
rvm:
- 2.1
script: "./script/cibuild"
sudo: false
deploy:
  provider: s3
  access_key_id: AKIAJ3DXDOUXZY5ZC3WA
  secret_access_key:
    secure: aAZf4SGdC67ckRgFMA38hBln5BPEt9fYFGyQmMUiZs20bIfIsYJaYoAuCxdYe7n6X8+OP34qBie/zsmXCcZzPOfwmoG0PZUSg2QtExsmy4dn0YX67X/T4/m+xRAWsVcuZqTFSoHz9oqdMMSiCSFx/wJ5fJtnrZIVczPAHA5w4QFtw+Mx854TyoJrjVcwN6MmpJJyY493ZoRYC4g1soY9Ff42lfzyI5sd+V8k0aQlXRt4upSSUmlqWxzAI/RL92GUW0nFZKQCQGbKizyM6winpB3XGJh/g1W+jdEzk4JrsBwgpUxWdgZcO0r9yZNE6Nb7SlhnmsoBO0I1UpZT1iAF0TNN/UvNsaILxbuIBquhpyS6PiNZsg9xBvyn4BQZb06PvRnpLCXVn0QRZP5yaTcLkJ81iO0toeabHhI7XtfrzbA+DrKaIxXpk3XTYoUQj//vS9jkY7ldZIYubns18Cac3WriGX3X2c6nKkOCOGeIY4n8anVmHivvxAa0QzpT4ENsGjo8s8N0usrkLc6uDbcfV5nAIBNJOozqyf1wWrMWpEckBBYt8cJhrfJrEaMUk4xQdf2gKk/fdn7gT4odHUUpxuf7KrzBCMdYTxz3LzI5emizyOh8bbr+IXWZXZoVkRmSGbIvZQq1pAPL0v7OqvpYX5iRaOxMikarcVkaKlhMcxU=
  bucket: mollytenenbaum.com
  region: us-west-2
  local_dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    repo: dandante/mt.com
