---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Molly Tenenbaum, poet and old-time banjo player in Seattle, is the author
  of NOW and BY A THREAD. Her CDs are INSTEAD OF A PONY and GOOSE AND GANDER.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
